### PR TITLE
Hotfix issue #005

### PR DESCRIPTION
**Pull request by piotrhoppe**
Please merge.

### CODE REVIEW

**Comment by piotrhoppe** [comment]
When are you plan release the new version? Did you tested this branch?

**Comment by phstc** [comment]
Hey @piotrhoppe, I'm downloading FF to test it today. If all is working I will submit the new version. Great works, super thanks :beers:

**Comment by phstc** [comment]
Alright, all good. New release submitted - I'm waiting Mozilla's approval.

**Comment by phstc** [comment]
BTW I merged both of your Pull Requests, is this code https://github.com/phstc/gesture-translate/blob/master/src/chrome/content/gesturegoogtrans/GoogleTranslate.js the one you wanted to merge?

**Comment by piotrhoppe** [comment]
Yes it is.

**Comment by phstc** [comment]
Hi @piotrhoppe 

I'm still getting errors from the Mozilla validation. Can I add you as an author so you can manage this new release? If so, what's your email?

screen shot 2015-09-01 at 5 27 02 pm

```
Your add-on, Gesture Translate 0.6.1, has been preliminarily reviewed by an editor and is now available for download in our gallery at https://addons.mozilla.org/addon/gesture-translate/


Reviewer:
Andrey Meshkov

Comments:
Your preliminary review request has been approved.

This version didn't pass full review because of the following issues:

1) Errors in the Browser Console:
TypeError: refreshBlocklist is not a function options.xul:1:0

2) `<prefwindow>` elements must have IDs.

You need to correct them to get full approval. Thanks.
```

**Comment by piotrhoppe** [comment]
Of Course you can add me to authors. Please use this email:
piotr.hoppe.tel@gmail.com

2015-09-01 22:27 GMT+02:00 Pablo Cantero notifications@github.com:

> Hi @piotrhoppe https://github.com/piotrhoppe
> 
> I'm still getting errors from the Mozilla validation. Can I add you as an
> author so you can manage this new release? If so, what's your email?
> 
> [image: screen shot 2015-09-01 at 5 27 02 pm]
> https://cloud.githubusercontent.com/assets/105652/9615484/b735bee4-50ce-11e5-83c4-d274e9f3e69b.png
> 
> Your add-on, Gesture Translate 0.6.1, has been preliminarily reviewed by an editor and is now available for download in our gallery at https://addons.mozilla.org/addon/gesture-translate/
> 
> Reviewer:
> Andrey Meshkov
> 
> Comments:
> Your preliminary review request has been approved.
> 
> This version didn't pass full review because of the following issues:
> 
> 1) Errors in the Browser Console:
> TypeError: refreshBlocklist is not a function options.xul:1:0
> 
> 2) `<prefwindow>` elements must have IDs.
> 
> You need to correct them to get full approval. Thanks.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/phstc/gesture-translate/pull/7#issuecomment-136852097
> .

## 

Piotr Hoppe

**Comment by phstc** [comment]
@piotrhoppe awesome :smile: Could you create an account at addons.mozilla.org first? Otherwise I can't associate you.

**Comment by piotrhoppe** [comment]
Ok done. My username on addons.mozilla.org is p_hoppe. I use same e-mail 
what I gave you.

W dniu 03.09.2015 o 17:47, Pablo Cantero pisze:

> @piotrhoppe https://github.com/piotrhoppe awesome :smile: Could you 
> create an account at addons.mozilla.org first? Otherwise I can't 
> associate you.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/phstc/gesture-translate/pull/7#issuecomment-137490658.

## 

Piotr Hoppe

**Comment by phstc** [comment]
Awesome. Just added you. Feel free to re-submit your patch to them. Thanks again :beers:

**Comment by piotrhoppe** [comment]
When I run validation I can see only warnings.

2015-09-04 14:39 GMT+02:00 Pablo Cantero notifications@github.com:

> Awesome. Just added you. Feel free to re-submit your patch to them. Thanks
> again [image: :beers:]
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/phstc/gesture-translate/pull/7#issuecomment-137725894
> .

## 

Piotr Hoppe

**Pull request merged**
